"""Restructure database and models modules

Revision ID: b9beff84a466
Revises: 
Create Date: 2026-01-13 15:43:51.186315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9beff84a466'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_siret'), 'companies', ['siret'], unique=True)
    op.create_table('openstreetmap_enrichi',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telephones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whatsapp', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_empty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_openstreetmap_enrichi_updated_at', 'openstreetmap_enrichi', ['updated_at'], unique=False)
    op.create_index('idx_openstreetmap_enrichi_website', 'openstreetmap_enrichi', ['website'], unique=False)
    op.create_index(op.f('ix_openstreetmap_enrichi_website'), 'openstreetmap_enrichi', ['website'], unique=True)
    op.create_table('pricing_plans',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('price_promo', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('price_promo_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_promo_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=False),
    sa.Column('max_prospects', sa.Integer(), nullable=True),
    sa.Column('max_prospects_per_hour', sa.Integer(), nullable=True),
    sa.Column('max_prospects_per_day', sa.Integer(), nullable=True),
    sa.Column('count_limit', sa.Integer(), nullable=True),
    sa.Column('geoloc_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_display', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(price_promo_start_date IS NULL AND price_promo_end_date IS NULL) OR (price_promo_start_date IS NOT NULL AND price_promo_end_date IS NOT NULL AND price_promo_end_date > price_promo_start_date)', name='check_promo_dates'),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_plans_billing_period', 'pricing_plans', ['billing_period'], unique=False)
    op.create_index('idx_pricing_plans_is_active', 'pricing_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_plans_billing_period'), 'pricing_plans', ['billing_period'], unique=False)
    op.create_index(op.f('ix_pricing_plans_is_active'), 'pricing_plans', ['is_active'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('search_types',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_types_is_active'), 'search_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_search_types_name'), 'search_types', ['name'], unique=True)
    op.create_table('test_table',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('abonnements',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pricing_plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='check_end_after_start'),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abonnements_user_active', 'abonnements', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_abonnements_end_date'), 'abonnements', ['end_date'], unique=False)
    op.create_index(op.f('ix_abonnements_is_active'), 'abonnements', ['is_active'], unique=False)
    op.create_index(op.f('ix_abonnements_pricing_plan_id'), 'abonnements', ['pricing_plan_id'], unique=False)
    op.create_index(op.f('ix_abonnements_user_id'), 'abonnements', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('black_list',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_list_date_end'), 'black_list', ['date_end'], unique=False)
    op.create_index(op.f('ix_black_list_email'), 'black_list', ['email'], unique=True)
    op.create_index(op.f('ix_black_list_is_active'), 'black_list', ['is_active'], unique=False)
    op.create_index(op.f('ix_black_list_user_id'), 'black_list', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('language', sa.String(), server_default=sa.text("'fr'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index(op.f('ix_profiles_company_id'), 'profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('search_history',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('search_type_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('results_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('filters_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_type_id'], ['search_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_history_user_created', 'search_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_search_type_id'), 'search_history', ['search_type_id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('search_history_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('result_type', sa.String(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_history_id'], ['search_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_created_at'), 'search_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_results_result_type'), 'search_results', ['result_type'], unique=False)
    op.create_index(op.f('ix_search_results_search_history_id'), 'search_results', ['search_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_search_history_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_result_type'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_created_at'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_search_type_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_index('idx_search_history_user_created', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_company_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_black_list_user_id'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_is_active'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_email'), table_name='black_list')
    op.drop_index(op.f('ix_black_list_date_end'), table_name='black_list')
    op.drop_table('black_list')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_abonnements_user_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_pricing_plan_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_is_active'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_end_date'), table_name='abonnements')
    op.drop_index('idx_abonnements_user_active', table_name='abonnements')
    op.drop_table('abonnements')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('test_table')
    op.drop_index(op.f('ix_search_types_name'), table_name='search_types')
    op.drop_index(op.f('ix_search_types_is_active'), table_name='search_types')
    op.drop_table('search_types')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_pricing_plans_is_active'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_billing_period'), table_name='pricing_plans')
    op.drop_index('idx_pricing_plans_is_active', table_name='pricing_plans')
    op.drop_index('idx_pricing_plans_billing_period', table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_openstreetmap_enrichi_website'), table_name='openstreetmap_enrichi')
    op.drop_index('idx_openstreetmap_enrichi_website', table_name='openstreetmap_enrichi')
    op.drop_index('idx_openstreetmap_enrichi_updated_at', table_name='openstreetmap_enrichi')
    op.drop_table('openstreetmap_enrichi')
    op.drop_index(op.f('ix_companies_siret'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
